### ISSUE TITLE
EnderDragonGirl and WAILA crash

### ISSUE THREAD

**Issue by Jukari** [DoctorWiggles/GrimoireOfGaia#5]
java.lang.NullPointerException: Saving entity NBT
	at gaia.entity.monster.EntityGaiaEnderDragonGirl.func_70014_b(EntityGaiaEnderDragonGirl.java:118)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1582)
	at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:137)
	at net.darkhax.wawla.engine.waila.EntityProvider.getWailaOverride(EntityProvider.java:22)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierEntity(RayTracing.java:122)
	at mcp.mobius.waila.overlay.RayTracing.getTargetEntity(RayTracing.java:74)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_603_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Looks like something between looking at the ender dragon girl and waila trying to pull info on it is causing a crash

Disabling WAILA fixes the crash at the moment

**Comment by DoctorWiggles** [comment]
I couldn't seem to reproduce that error, but I did find an issue that might had been causing it.
[It ~_should_~ be fixed in version 1.4.4](https://github.com/DoctorWiggles/GrimoireOfGaia/releases/tag/1.4.0-ALPHA) - b1873db

Let me know if that works.

If it doesn't please post your java version, forge build and other mods you might be using.

**Comment by Jukari** [comment]
Yes, this update fixed it.

Thanks for the speedy fix, you're awesome!

**Comment by DoctorWiggles** [comment]
:^)
